# Generated by Django 3.2.10 on 2021-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('decr', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='decr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
