# Generated by Django 3.2.10 on 2021-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20211227_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='decr',
            field=models.TextField(verbose_name=''),
        ),
    ]
